import { useState, useEffect, useMemo, useCallback } from 'react';
import { LanguageContext } from './LanguageContext.js';

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = useCallback(() => {
    setLanguage(prev => (prev === 'pt' ? 'en' : 'pt'));
  }, []);

  const translate = useCallback((key) => translations[language][key] || key, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    toggleLanguage,
    t: translate
  }), [language, toggleLanguage, translate]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  pt: {
    'nav.home': 'Início',
    'nav.about': 'Sobre',
    'nav.projects': 'Projetos',
    'nav.skills': 'Skills',
    'nav.contact': 'Contato',
    'nav.main': 'Navegação principal',
    'theme.switchLight': 'Mudar para tema claro',
    'theme.switchDark': 'Mudar para tema escuro',
    
    'hero.role1': 'Software Engineering Student',
    'hero.role2': 'Web & APIs',
    'hero.headline': 'Higor Batista',
    'hero.description': 'Estudante de Engenharia de Software na FIAP, com experiência prática em aplicações web e APIs REST. Trabalho com Python, C#/.NET, React e dados, enquanto direciono minha formação para IA e Machine Learning.',
    'hero.eyebrow': 'SOFTWARE ENGINEERING',
    'hero.availability': 'OPEN TO INTERNSHIP / JUNIOR ROLES',
    'hero.viewProjects': 'Ver Projetos',
    'hero.contact': 'Fale Comigo',
    
    'stats.liveLabel': 'Status ao vivo — dados do GitHub',
    'stats.projects': 'Projetos no GitHub',
    'stats.stars': 'GitHub Stars',
    'stats.forks': 'Forks',
    'stats.experience': 'Anos de Exp.',
    'github.error': 'Não foi possível carregar os projetos do GitHub.',
    
    'about.title': 'Sobre Mim',
    'about.subtitle': 'Engenharia de Software | Desenvolvimento Web | IA & Dados',
    'about.card1.title': 'Quem sou eu?',
    'about.card1.text': 'Sou estudante de Engenharia de Software na FIAP, com experiência prática no desenvolvimento de aplicações web e APIs REST. Tenho interesse em construir soluções claras e orientadas a problemas reais.',
    'about.card2.title': 'O que eu faço?',
    'about.card2.text': 'Minha base técnica inclui Python, C#, SQL, React, .NET, Node.js e bancos de dados como PostgreSQL, MySQL e MongoDB, além de integração com APIs e ferramentas de desenvolvimento.',
    'about.card3.title': 'Meu código',
    'about.card3.text': 'Atualmente direciono minha formação para Inteligência Artificial, Machine Learning e análise de dados, buscando uma oportunidade de estágio ou nível júnior em tecnologia.',
    'about.global': 'Global',
    'about.remote': 'Trabalho Remoto',
    'about.fullstack': 'Full Stack',
    'about.frontback': 'Front + Back',
    'about.education': 'FIAP',
    'about.degree': 'Engenharia de Software',
    'about.web': 'Web',
    'about.apis': 'APIs REST',
    'about.codeBlock': `const developer = {
  name: "Higor Batista",
  role: "Software Development / AI & Data",
  location: "Brasil 🇧🇷",
  github: "higorxyz",
  repos: {repos},
  stars: {stars},
    code: ["Python", "C#", "JavaScript", 
      "TypeScript", "SQL"],
    backend: ["ASP.NET Core", ".NET", "Node.js",
         "REST APIs", "JWT"],
    frontend: ["React", "Next.js", "Vite", 
          "Tailwind CSS"],
    data: ["PostgreSQL", "MySQL", "MongoDB"],
    currentFocus: "AI, Machine Learning & Data"
};`,
    'about.downloadCV': 'Ver Currículo',
    'cv.label': 'HIGOR BATISTA',
    'cv.zoomIn': 'Aumentar zoom',
    'cv.zoomOut': 'Reduzir zoom',
    'cv.loading': 'Carregando currículo...',
    'cv.error': 'Não foi possível renderizar o currículo.',
    'cv.download': 'Baixar PDF',
    'modal.close': 'Fechar',
    
    'projects.title': 'Projetos',
    'projects.subtitle': 'Alguns dos meus trabalhos recentes',
    'projects.autoUpdate': '(Atualizados automaticamente do GitHub)',
    'projects.search': 'Buscar projetos por nome, tecnologia ou descrição...',
    'projects.all': 'Todos',
    'projects.featured': 'Destaque',
    'projects.live': 'Live',
    'projects.repo': 'Repo',
    'projects.beta': 'Beta',
    'projects.preview': 'Preview',
    'projects.previewTitle': 'Pulseboard API',
    'projects.previewDescription': 'Projeto de demonstração para visualizar a composição dos cards enquanto a conexão com o GitHub está indisponível.',
    'projects.code': 'Code',
    'projects.viewDetails': 'Ver Detalhes',
    'projects.viewSite': 'Ver Site',
    'projects.viewRepo': 'Ver Repo',
    'projects.viewMore': 'Ver Mais no GitHub',
    'projects.viewMoreGitHub': 'Ver Mais no GitHub',
    'projects.readmeFull': 'Ver README completo',
    'projects.visits': 'visitas',
    'projects.noResults': 'Nenhum projeto encontrado',
    'projects.noData': 'Nenhum projeto disponível no momento.',
    'projects.noDataHint': 'Os projetos são carregados diretamente do GitHub.',
    'projects.oneResult': '1 projeto encontrado',
    'projects.multipleResults': '{count} projetos encontrados',
    'projects.searchTips': '💡 Dicas de busca:',
    'projects.tip1': '• Digite o nome do projeto',
    'projects.tip2': '• Busque por tecnologia (ex: "React", "Python")',
    'projects.tip3': '• Procure por palavras na descrição',
    
    'modal.preview': 'Preview AO VIVO do Site',
    'modal.open': 'Abrir',
    'modal.projectDetails': 'Detalhes do Projeto',
    'modal.readme': 'README',
    'modal.loading': 'Carregando README...',
    'modal.noReadme': 'Este projeto não tem um README',
    'modal.stats': 'Estatísticas',
    'modal.stars': 'Stars',
    'modal.forks': 'Forks',
    'modal.watchers': 'Watchers',
    'modal.created': 'Criado em',
    'modal.updated': 'Atualizado',
    'modal.language': 'Linguagem',
    'modal.technologies': 'Tecnologias',
    'modal.links': 'Links',
    'modal.viewGithub': 'Ver no GitHub',
    'modal.viewDemo': 'Ver Demo',
    
    'readme.viewFull': 'Ver README completo',
    'readme.title': 'Documentação do Projeto',
    'readme.loading': 'Carregando README...',
    'readme.notAvailable': 'README não disponível',
    'readme.noFile': 'Este projeto não possui um arquivo README.md',
    'readme.close': 'Fechar (ESC)',
    
    'skills.title': 'Habilidades',
    'skills.subtitle': 'Uma base prática em desenvolvimento web, APIs e dados, com foco crescente em Inteligência Artificial.',
    'skills.basedOn': '(Baseado nos meus repositórios)',
    'skills.mobile': 'Mobile',
    'skills.devops': 'DevOps',
    'skills.datascience': 'Data Science',
    'skills.systems': 'Systems',
    'skills.other': 'Outras',
    'skills.programming': 'Programação',
    'skills.backend': 'Backend & APIs',
    'skills.frontend': 'Frontend',
    'skills.data': 'Dados & IA',
    'skills.tools': 'Ferramentas',
    'skills.noteLabel': 'COMO EU TRABALHO',
    'skills.noteTitle': 'Tecnologia é meio. O problema vem primeiro.',
    'skills.noteText': 'Minha base combina desenvolvimento web, APIs REST e bancos de dados. Hoje também direciono minha formação para Inteligência Artificial, Machine Learning e soluções orientadas a dados.',
    'skills.noteOne': 'Construção prática',
    'skills.noteTwo': 'Aprendizado contínuo',
    
    'contact.title': 'Contato',
    'contact.subtitle': 'Vamos trabalhar juntos?',
    'contact.email': 'Email',
    'contact.location': 'Localização',
    'contact.locationValue': 'Brasil 🇧🇷',
    'contact.response': 'Resposta',
    'contact.responseTime': 'Geralmente em até 24h',
    'contact.form.name': 'Seu Nome',
    'contact.form.email': 'Seu Email',
    'contact.form.message': 'Sua Mensagem',
    'contact.form.send': 'Enviar Mensagem',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': 'Mensagem enviada com sucesso!',
    'contact.form.errorShort': 'Erro ao enviar',
    'contact.form.error': 'Erro ao enviar mensagem. Tente novamente.',
    'contact.social': 'Ou me encontre nas redes',
    
    'footer.made': 'Desenvolvido por Higor Batista',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.version': 'Versão',
    
    'loading.init': 'Inicializando portfólio...',
    'loading.projects': 'Carregando projetos...',
    'loading.github': 'Conectando ao GitHub...',
    'loading.experience': 'Preparando experiência...',
    'loading.almost': 'Quase lá...',
    'loading.loading': 'Loading...',
    'loading.version': 'Powered by React + GitHub API',
    
    'contributions.title': 'contribuições no último ano',
    'contributions.heading': 'Atividade recente',
    'contributions.less': 'Menos',
    'contributions.more': 'Mais',
    'contributions.loading': 'Carregando contribuições...',
    'contributions.contribution': 'contribuição',
    'contributions.contributions': 'contribuições',
  },
  
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.projects': 'Projects',
    'nav.skills': 'Skills',
    'nav.contact': 'Contact',
    'nav.main': 'Main navigation',
    'theme.switchLight': 'Switch to light theme',
    'theme.switchDark': 'Switch to dark theme',
    
    'hero.role1': 'Software Engineering Student',
    'hero.role2': 'Web & APIs',
    'hero.headline': 'Higor Batista',
    'hero.description': 'Software Engineering student at FIAP with hands-on experience building web applications and REST APIs. I work with Python, C#/.NET, React and data, while directing my studies toward AI and Machine Learning.',
    'hero.eyebrow': 'SOFTWARE ENGINEERING',
    'hero.availability': 'OPEN TO INTERNSHIP / JUNIOR ROLES',
    'hero.viewProjects': 'View Projects',
    'hero.contact': 'Contact Me',
    
    'stats.liveLabel': 'Live status — data from GitHub',
    'stats.projects': 'GitHub Projects',
    'stats.stars': 'GitHub Stars',
    'stats.forks': 'Forks',
    'stats.experience': 'Years of Exp.',
    'github.error': 'Unable to load projects from GitHub.',
    
    'about.title': 'About Me',
    'about.subtitle': 'Software Engineering | Web Development | AI & Data',
    'about.card1.title': 'Who am I?',
    'about.card1.text': 'I am a Software Engineering student at FIAP with hands-on experience developing web applications and REST APIs. I am interested in building clear solutions for real problems.',
    'about.card2.title': 'What do I do?',
    'about.card2.text': 'My technical foundation includes Python, C#, SQL, React, .NET, Node.js and databases such as PostgreSQL, MySQL and MongoDB, along with API integration and development tools.',
    'about.card3.title': 'My code',
    'about.card3.text': 'I am currently directing my studies toward Artificial Intelligence, Machine Learning and data analysis, while seeking an internship or junior opportunity in technology.',
    'about.global': 'Global',
    'about.remote': 'Remote Work',
    'about.fullstack': 'Full Stack',
    'about.frontback': 'Front + Back',
    'about.education': 'FIAP',
    'about.degree': 'Software Engineering',
    'about.web': 'Web',
    'about.apis': 'REST APIs',
    'about.codeBlock': `const developer = {
  name: "Higor Batista",
  role: "Software Development / AI & Data",
  location: "Brazil 🇧🇷",
  github: "higorxyz",
  repos: {repos},
  stars: {stars},
    code: ["Python", "C#", "JavaScript", 
      "TypeScript", "SQL"],
    backend: ["ASP.NET Core", ".NET", "Node.js",
         "REST APIs", "JWT"],
    frontend: ["React", "Next.js", "Vite", 
          "Tailwind CSS"],
    data: ["PostgreSQL", "MySQL", "MongoDB"],
    currentFocus: "AI, Machine Learning & Data"
};`,
    'about.downloadCV': 'View CV',
    'cv.label': 'HIGOR BATISTA',
    'cv.zoomIn': 'Zoom in',
    'cv.zoomOut': 'Zoom out',
    'cv.loading': 'Loading resume...',
    'cv.error': 'Unable to render the resume.',
    'cv.download': 'Download PDF',
    'modal.close': 'Close',
    
    'projects.title': 'Projects',
    'projects.subtitle': 'Some of my recent work',
    'projects.autoUpdate': '(Automatically updated from GitHub)',
    'projects.search': 'Search projects by name, technology or description...',
    'projects.all': 'All',
    'projects.featured': 'Featured',
    'projects.live': 'Live',
    'projects.repo': 'Repo',
    'projects.beta': 'Beta',
    'projects.preview': 'Preview',
    'projects.previewTitle': 'Pulseboard API',
    'projects.previewDescription': 'Demo project to preview the card layout while the GitHub connection is unavailable.',
    'projects.code': 'Code',
    'projects.viewDetails': 'View Details',
    'projects.viewSite': 'View Site',
    'projects.viewRepo': 'View Repo',
    'projects.viewMore': 'View More on GitHub',
    'projects.viewMoreGitHub': 'View More on GitHub',
    'projects.readmeFull': 'View full README',
    'projects.visits': 'visits',
    'projects.noResults': 'No projects found',
    'projects.noData': 'No projects are available right now.',
    'projects.noDataHint': 'Projects are loaded directly from GitHub.',
    'projects.oneResult': '1 project found',
    'projects.multipleResults': '{count} projects found',
    'projects.searchTips': '💡 Search tips:',
    'projects.tip1': '• Type the project name',
    'projects.tip2': '• Search by technology (e.g., "React", "Python")',
    'projects.tip3': '• Look for words in the description',
    
    'modal.preview': 'LIVE Site Preview',
    'modal.open': 'Open',
    'modal.projectDetails': 'Project Details',
    'modal.readme': 'README',
    'modal.loading': 'Loading README...',
    'modal.noReadme': 'This project doesn\'t have a README',
    'modal.stats': 'Statistics',
    'modal.stars': 'Stars',
    'modal.forks': 'Forks',
    'modal.watchers': 'Watchers',
    'modal.created': 'Created on',
    'modal.updated': 'Updated',
    'modal.language': 'Language',
    'modal.technologies': 'Technologies',
    'modal.links': 'Links',
    'modal.viewGithub': 'View on GitHub',
    'modal.viewDemo': 'View Demo',
    
    'readme.viewFull': 'View full README',
    'readme.title': 'Project Documentation',
    'readme.loading': 'Loading README...',
    'readme.notAvailable': 'README not available',
    'readme.noFile': 'This project does not have a README.md file',
    'readme.close': 'Close (ESC)',
    
    'skills.title': 'Skills',
    'skills.subtitle': 'Hands-on experience across web development, APIs and data, with a growing focus on Artificial Intelligence.',
    'skills.basedOn': '(Based on my repositories)',
    'skills.mobile': 'Mobile',
    'skills.devops': 'DevOps',
    'skills.datascience': 'Data Science',
    'skills.systems': 'Systems',
    'skills.other': 'Other',
    'skills.programming': 'Programming',
    'skills.backend': 'Backend & APIs',
    'skills.frontend': 'Frontend',
    'skills.data': 'Data & AI',
    'skills.tools': 'Tools',
    'skills.noteLabel': 'HOW I WORK',
    'skills.noteTitle': 'Technology is the means. The problem comes first.',
    'skills.noteText': 'My foundation combines web development, REST APIs and databases. I am also directing my studies toward Artificial Intelligence, Machine Learning and data-driven solutions.',
    'skills.noteOne': 'Hands-on building',
    'skills.noteTwo': 'Continuous learning',
    
    'contact.title': 'Contact',
    'contact.subtitle': "Let's work together?",
    'contact.email': 'Email',
    'contact.location': 'Location',
    'contact.locationValue': 'Brazil 🇧🇷',
    'contact.response': 'Response',
    'contact.responseTime': 'Usually within 24h',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Your Email',
    'contact.form.message': 'Your Message',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully!',
    'contact.form.errorShort': 'Unable to send',
    'contact.form.error': 'Unable to send message. Please try again.',
    'contact.social': 'Or find me on social media',
    
    'footer.made': 'Made by Higor Batista',
    'footer.rights': 'All rights reserved.',
    'footer.version': 'Version',
    
    'loading.init': 'Initializing portfolio...',
    'loading.projects': 'Loading projects...',
    'loading.github': 'Connecting to GitHub...',
    'loading.experience': 'Preparing experience...',
    'loading.almost': 'Almost there...',
    'loading.loading': 'Loading...',
    'loading.version': 'Powered by React + GitHub API',
    
    'contributions.title': 'contributions in the last year',
    'contributions.heading': 'Recent activity',
    'contributions.less': 'Less',
    'contributions.more': 'More',
    'contributions.loading': 'Loading contributions...',
    'contributions.contribution': 'contribution',
    'contributions.contributions': 'contributions',
  }
};
