import { useState, useEffect, useMemo, useCallback } from 'react';
import { LanguageContext } from './LanguageContext.js';

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = useCallback(() => {
    setLanguage(prev => (prev === 'pt' ? 'en' : 'pt'));
  }, []);

  const translate = useCallback((key) => translations[language][key] || key, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    toggleLanguage,
    t: translate
  }), [language, toggleLanguage, translate]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  pt: {
    'nav.home': 'Início',
    'nav.about': 'Sobre',
    'nav.projects': 'Projetos',
    'nav.skills': 'Skills',
    'nav.contact': 'Contato',
    
    'hero.role1': 'Software Developer',
    'hero.role2': 'Higor Batista',
    'hero.description': 'Transformando ideias 💡 em código e criando experiências digitais que impressionam',
    'hero.viewProjects': 'Ver Projetos',
    'hero.contact': 'Fale Comigo',
    
    'stats.projects': 'Projetos no GitHub',
    'stats.stars': 'GitHub Stars',
    'stats.forks': 'Forks',
    'stats.experience': 'Anos de Exp.',
    
    'about.title': 'Sobre Mim',
    'about.subtitle': 'Desenvolvedor apaixonado por tecnologia',
    'about.card1.title': 'Quem sou eu?',
    'about.card1.text': '🚀 Sou um desenvolvedor apaixonado por criar soluções inovadoras que fazem a diferença. Com expertise em desenvolvimento web full-stack, transformo ideias complexas em produtos elegantes e funcionais.',
    'about.card2.title': 'O que eu faço?',
  'about.card2.text': '💡 Estudante de Engenharia de Software com maior vivência em JavaScript, C++, Python, React e SQL. Sigo explorando novas tecnologias e metodologias para entregar experiências cada vez melhores.',
    'about.card3.title': 'Meu código',
    'about.card3.text': '🚀 Quando não estou codando, você pode me encontrar explorando novas tecnologias, contribuindo para projetos open source, ou estudando e planejando a próxima inovação!',
    'about.global': 'Global',
    'about.remote': 'Trabalho Remoto',
    'about.fullstack': 'Full Stack',
    'about.frontback': 'Front + Back',
    'about.codeBlock': `const developer = {
  name: "Higor Batista",
  role: "Full Stack Developer",
  location: "Brasil 🇧🇷",
  github: "higorxyz",
  repos: {repos},
  stars: {stars},
  code: ["JavaScript", "TypeScript", 
         "Python", "SQL"],
  tools: ["React", "Next.js", "Node.js",
          "Tailwind", "PostgreSQL"],
  architecture: ["SPA", "SSR", 
                 "Microservices"],
  currentFocus: "Building amazing UX",
  lifePhilosophy: "Code is poetry ✨",
  funFact: "Debug by day, dream by night",
  passion: "🚀 Innovation & Tech"
};`,
    'about.downloadCV': 'Download CV',
    
    'projects.title': 'Projetos',
    'projects.subtitle': 'Alguns dos meus trabalhos recentes',
    'projects.autoUpdate': '(Atualizados automaticamente do GitHub)',
    'projects.search': 'Buscar projetos por nome, tecnologia ou descrição...',
    'projects.all': 'Todos',
    'projects.featured': 'Destaque',
    'projects.live': 'Live',
    'projects.repo': 'Repo',
    'projects.code': 'Code',
    'projects.viewDetails': 'Ver Detalhes',
    'projects.viewSite': 'Ver Site',
    'projects.viewRepo': 'Ver Repo',
    'projects.viewMore': 'Ver Mais no GitHub',
    'projects.viewMoreGitHub': 'Ver Mais no GitHub',
    'projects.readmeFull': 'Ver README completo',
    'projects.visits': 'visitas',
    'projects.noResults': 'Nenhum projeto encontrado',
    'projects.oneResult': '1 projeto encontrado',
    'projects.multipleResults': '{count} projetos encontrados',
    'projects.searchTips': '💡 Dicas de busca:',
    'projects.tip1': '• Digite o nome do projeto',
    'projects.tip2': '• Busque por tecnologia (ex: "React", "Python")',
    'projects.tip3': '• Procure por palavras na descrição',
    
    'modal.preview': 'Preview AO VIVO do Site',
    'modal.open': 'Abrir',
    'modal.projectDetails': 'Detalhes do Projeto',
    'modal.readme': 'README',
    'modal.loading': 'Carregando README...',
    'modal.noReadme': 'Este projeto não tem um README',
    'modal.stats': 'Estatísticas',
    'modal.stars': 'Stars',
    'modal.forks': 'Forks',
    'modal.watchers': 'Watchers',
    'modal.created': 'Criado em',
    'modal.updated': 'Atualizado',
    'modal.language': 'Linguagem',
    'modal.technologies': 'Tecnologias',
    'modal.links': 'Links',
    'modal.viewGithub': 'Ver no GitHub',
    'modal.viewDemo': 'Ver Demo',
    
    'readme.viewFull': 'Ver README completo',
    'readme.title': 'Documentação do Projeto',
    'readme.loading': 'Carregando README...',
    'readme.notAvailable': 'README não disponível',
    'readme.noFile': 'Este projeto não possui um arquivo README.md',
    'readme.close': 'Fechar (ESC)',
    
    'skills.title': 'Habilidades',
    'skills.subtitle': 'Tecnologias com as quais trabalho atualmente',
    'skills.basedOn': '(Baseado nos meus repositórios)',
    'skills.frontend': 'Frontend',
    'skills.backend': 'Backend',
    'skills.mobile': 'Mobile',
    'skills.devops': 'DevOps',
    'skills.datascience': 'Data Science',
    'skills.systems': 'Systems',
    'skills.other': 'Outras',
    
    'contact.title': 'Contato',
    'contact.subtitle': 'Vamos trabalhar juntos?',
    'contact.email': 'Email',
    'contact.location': 'Localização',
    'contact.locationValue': 'Brasil 🇧🇷',
    'contact.response': 'Resposta',
    'contact.responseTime': 'Dentro de 24h ⚡',
    'contact.form.name': 'Seu Nome',
    'contact.form.email': 'Seu Email',
    'contact.form.message': 'Sua Mensagem',
    'contact.form.send': 'Enviar Mensagem',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': 'Mensagem enviada com sucesso!',
    'contact.social': 'Ou me encontre nas redes',
    
    'footer.made': 'Desenvolvido com 💜 e muita dedicação por Higor Batista',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.version': 'Versão',
    
    'loading.init': 'Inicializando portfólio...',
    'loading.projects': 'Carregando projetos...',
    'loading.github': 'Conectando ao GitHub...',
    'loading.experience': 'Preparando experiência...',
    'loading.almost': 'Quase lá...',
    'loading.loading': 'Loading...',
    'loading.version': 'Powered by React + GitHub API',
    
    'contributions.title': 'contribuições no último ano',
    'contributions.less': 'Menos',
    'contributions.more': 'Mais',
    'contributions.loading': 'Carregando contribuições...',
    'contributions.contribution': 'contribuição',
    'contributions.contributions': 'contribuições',
  },
  
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.projects': 'Projects',
    'nav.skills': 'Skills',
    'nav.contact': 'Contact',
    
    'hero.role1': 'Software Developer',
    'hero.role2': 'Higor Batista',
    'hero.description': 'Turning ideas 💡 into code and creating impressive digital experiences',
    'hero.viewProjects': 'View Projects',
    'hero.contact': 'Contact Me',
    
    'stats.projects': 'GitHub Projects',
    'stats.stars': 'GitHub Stars',
    'stats.forks': 'Forks',
    'stats.experience': 'Years of Exp.',
    
    'about.title': 'About Me',
    'about.subtitle': 'Developer passionate about technology',
    'about.card1.title': 'Who am I?',
    'about.card1.text': '🚀 Full Stack Developer passionate about creating innovative solutions that make a difference. With expertise in full-stack web development, I transform complex ideas into elegant and functional products.',
    'about.card2.title': 'What do I do?',
  'about.card2.text': '💡 Software Engineering student with hands-on experience in JavaScript, C++, Python, React and SQL. I keep exploring new technologies and practices to deliver better experiences.',
    'about.card3.title': 'My code',
    'about.card3.text': '🚀 When I\'m not coding, you can find me exploring new technologies, contributing to open source projects, or studying and planning the next innovation!',
    'about.global': 'Global',
    'about.remote': 'Remote Work',
    'about.fullstack': 'Full Stack',
    'about.frontback': 'Front + Back',
    'about.codeBlock': `const developer = {
  name: "Higor Batista",
  role: "Full Stack Developer",
  location: "Brazil 🇧🇷",
  github: "higorxyz",
  repos: {repos},
  stars: {stars},
  code: ["JavaScript", "TypeScript", 
         "Python", "SQL"],
  tools: ["React", "Next.js", "Node.js",
          "Tailwind", "PostgreSQL"],
  architecture: ["SPA", "SSR", 
                 "Microservices"],
  currentFocus: "Building amazing UX",
  lifePhilosophy: "Code is poetry ✨",
  funFact: "Debug by day, dream by night",
  passion: "🚀 Innovation & Tech"
};`,
    'about.downloadCV': 'Download CV',
    
    'projects.title': 'Projects',
    'projects.subtitle': 'Some of my recent work',
    'projects.autoUpdate': '(Automatically updated from GitHub)',
    'projects.search': 'Search projects by name, technology or description...',
    'projects.all': 'All',
    'projects.featured': 'Featured',
    'projects.live': 'Live',
    'projects.repo': 'Repo',
    'projects.code': 'Code',
    'projects.viewDetails': 'View Details',
    'projects.viewSite': 'View Site',
    'projects.viewRepo': 'View Repo',
    'projects.viewMore': 'View More on GitHub',
    'projects.viewMoreGitHub': 'View More on GitHub',
    'projects.readmeFull': 'View full README',
    'projects.visits': 'visits',
    'projects.noResults': 'No projects found',
    'projects.oneResult': '1 project found',
    'projects.multipleResults': '{count} projects found',
    'projects.searchTips': '💡 Search tips:',
    'projects.tip1': '• Type the project name',
    'projects.tip2': '• Search by technology (e.g., "React", "Python")',
    'projects.tip3': '• Look for words in the description',
    
    'modal.preview': 'LIVE Site Preview',
    'modal.open': 'Open',
    'modal.projectDetails': 'Project Details',
    'modal.readme': 'README',
    'modal.loading': 'Loading README...',
    'modal.noReadme': 'This project doesn\'t have a README',
    'modal.stats': 'Statistics',
    'modal.stars': 'Stars',
    'modal.forks': 'Forks',
    'modal.watchers': 'Watchers',
    'modal.created': 'Created on',
    'modal.updated': 'Updated',
    'modal.language': 'Language',
    'modal.technologies': 'Technologies',
    'modal.links': 'Links',
    'modal.viewGithub': 'View on GitHub',
    'modal.viewDemo': 'View Demo',
    
    'readme.viewFull': 'View full README',
    'readme.title': 'Project Documentation',
    'readme.loading': 'Loading README...',
    'readme.notAvailable': 'README not available',
    'readme.noFile': 'This project does not have a README.md file',
    'readme.close': 'Close (ESC)',
    
    'skills.title': 'Skills',
    'skills.subtitle': 'Technologies I currently work with',
    'skills.basedOn': '(Based on my repositories)',
    'skills.frontend': 'Frontend',
    'skills.backend': 'Backend',
    'skills.mobile': 'Mobile',
    'skills.devops': 'DevOps',
    'skills.datascience': 'Data Science',
    'skills.systems': 'Systems',
    'skills.other': 'Other',
    
    'contact.title': 'Contact',
    'contact.subtitle': "Let's work together?",
    'contact.email': 'Email',
    'contact.location': 'Location',
    'contact.locationValue': 'Brazil 🇧🇷',
    'contact.response': 'Response',
    'contact.responseTime': 'Within 24h ⚡',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Your Email',
    'contact.form.message': 'Your Message',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully!',
    'contact.social': 'Or find me on social media',
    
    'footer.made': 'Made with 💜 and lots of dedication by Higor Batista',
    'footer.rights': 'All rights reserved.',
    'footer.version': 'Version',
    
    'loading.init': 'Initializing portfolio...',
    'loading.projects': 'Loading projects...',
    'loading.github': 'Connecting to GitHub...',
    'loading.experience': 'Preparing experience...',
    'loading.almost': 'Almost there...',
    'loading.loading': 'Loading...',
    'loading.version': 'Powered by React + GitHub API',
    
    'contributions.title': 'contributions in the last year',
    'contributions.less': 'Less',
    'contributions.more': 'More',
    'contributions.loading': 'Loading contributions...',
    'contributions.contribution': 'contribution',
    'contributions.contributions': 'contributions',
  }
};
